# Generated by Django 6.1.1 on 2026-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowings",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="borrowings",
            name="borrow_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
